### ISSUE TITLE
Any interest in a "formatter" feature?  and a bug...

### ISSUE THREAD

**Issue by colinta** [berzniz/backbone.getters.setters#1]
The bug is related to prototyping object, which _shouldn't_ be done, but _is_ :smile:, so worth watching out for:

``` javascript
// Go over all the set attributes and call the setter if available
for (attr in attrs) {}  # if Object.prototype has been changed, this will include those changes
for (attr in _(attrs).keys()) {}  // by the power of underscore, not no mo'.
```

The feature is one I baked into getters.setters today, that allows for a "formatter" to be passed into the getter/setters.

``` javascript
var m = new MyModel();
m.get('datetime');  // => Date object
m.get('datetime', 'time');  // => e.g. '13:45:12'
// WUH!?

var MyModel = Backbone.GSModel.extend({
  getters: {
    datetime: function(format) {
      var ret = this.rawget('datetime');  // also added, to make this easier.  calls Backbone.model.get.
      if ( format == 'time' ) {
        var time = ret.hour + ':' + ret.minute + ':' + ret.second;
        // real version has string padding, am/pm, etc.
        return time;
        }
      return ret;
    }
  }
});
```

If you're interested, I'll format this as a pull request.

**Comment by colinta** [comment]
`for (attr in _(attrs).keys()) {}` is wrong!  I can't figure out a clever shorthand, but this works:

``` javascript
for (var attr in attrs) {
  if ( ! attrs.hasOwnProperty(attr) )
    continue;
  // ...
}
```

**Comment by berzniz** [comment]
Thanks for all the input.

**1. The prototyping bug.** can you include a scenario where the problem can be seen? In most cases, the backbone API for the "key" argument is a javascript object only (JSON) or a single key. Note that the original backbone source code includes the same kind of enumeration over the "attrs" variable inside the original "set" method.

However, there are bugs in the code that I haven't pushed into the repo yet, mainly not declaring "attrs", "attr" with a "var" before them. Will update this soon.  

**2. The "formatter feature".** I see the need for a more versatile getter method, but I think this can be done in a simpler way.

One option that comes to mind is getting the "datetime" Date object and manipulating it using external methods. I think the date methods should be implemented on the Date object itself (check out date.js for a better javascript Date object).

For other tasks requiring methods on the backbone object, Another option is having multiple getter methods, one for each need (might not be suitable for the date-format task, but pretty useful for others): "timedate" and "timedateHHMMSS".

**3. The raw-get function** is good, but this might lead developers into calling this directly on the object and therefore "jumping over" the getter method. The idea is to have all get calls redirected into one getter method (I understand anyone can just call Backbone.Model.prototype.set.call but making this more accessible is not always recommended).

**What do you think?** I'm trying to favor small and simple code-base over more features.

**Comment by colinta** [comment]
The prototyping bug is for people who add methods to `Object.prototype`.  _I_ don't do that, but there are still those masochists who use Prototype.

backbone and underscore sometimes (not always!) use `for ( prop in attars ) {}`, but they also use `_.has` (a synonym for `Object.hasOwnProperty`), and the times they use one or the other depend on whether they want _all_ the attributes of the object or just the "keys" (case in point: they `_.keys` function uses `_.has`).

In this case, you only want the "setter-keys", not Object.prototype methods AND keys.

Next up.  Actually, `rawget` was _specifically_ to bypass the getters/setters!  So yeah, if you don't want a way to do that then drop 'em, for sure.

The formatter feature seems useful to me, I'm not sure how it could get "simpler", I'm just passing the format along to the getter/setter.  I won't try too hard to convince you.  It's something I got used to in my company's ORM (we call 'em "formatters", and there's a whole system for them).  I might even add this feature in my fork.

I think they makes things short and sweet, though it is a little magic...

``` javascript
Formatter.register('$', function(value) { return '$' + value; });
event.cost('$')  // => '$5.00'
```

Up to you!  Except the `Object.prototype` thing... :wink:

**Comment by zelibobla** [comment]
It looks like using model.toJSON() passing getters

**Comment by berzniz** [comment]
As I said, I'm trying to favor small and simple code-base over more features.
