### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by gillesruppert** [berzniz/backbone.getters.setters#3]
I've been using this plugin in the past and only now came to realise that you haven't included a license at all, which means nobody but you is really allowed to use this legally. 

If this is intended, it might be worth making a note of that in the README, but if it isn't it would be lovely if you could add a license such as MIT/BSD/WTFPL, so this can legitimately be used.

**Comment by slippers** [comment]
Ok, didn't know that.  I'll add one.

**Comment by gillesruppert** [comment]
Great, thanks!

**Comment by slippers** [comment]
Guiles,  ignore my response to this email.

**Comment by gillesruppert** [comment]
Do you mean you won't add a license? Sorry, I'm confused.

**Comment by berzniz** [comment]
MIT license added, thanks for requesting a license.

**Comment by slippers** [comment]
not my project,  i'm slippers not berzniz.  i was watching the project
and received your message.  sorry

**Comment by gillesruppert** [comment]
@slippers sorry, didn't realise. Was replying from the phone...
@berzniz thanks for taking care of this so swiftly!
