### ISSUE TITLE
model.toJSON() wont call getters  and return all properties 

### ISSUE THREAD

**Issue by jaseemabid** [berzniz/backbone.getters.setters#8]

**Comment by berzniz** [comment]
This is by design. Most use cases for getters are combining attributes or adding a transformation on another attribute. By using `toJSON`, you'll probably only want the "real" attributes and not the computed ones.

I'll leave it to a fork to add this if needed.

**Comment by jaseemabid** [comment]
Not sure what went through my head when I opened this ticket 5 months back. Makes sense.
